language: node_js
branches:
  except:
    - gh-pages
node_js:
  - 4
  - 6
  - 7
  - 8
before_script:
  - yarn build
script:
  - yarn cover:schema
after_success:
  - yarn cover:up
notifications:
  email: false
