sudo: required
dist: trusty
language: node_js
branches:
  except:
    - gh-pages
node_js:
  - 6
  - 8
  - 9
  - 10
  - 11
  - 12
before_script:
  - make build
script:
  - make test
after_success:
  - npm run codecov
notifications:
  email: false
